{% set name = "econml" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/econml-{{ version }}.tar.gz
  sha256: 4a8196d6c785e9e0e42b2fa35dd058eb37166c75dcdb90ada953feea6fbb854b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - dowhy
    - lightgbm
    - python-graphviz
    - joblib >=0.13.0
    - numba !=0.42.1
    - numpy
    - pandas
    - python
    - scikit-learn >=0.24
    - scipy >1.4.0
    - shap 0.38.1
    - sparse
    - statsmodels >=0.9

test:
  imports:
    - econml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/EconML
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
