{% set name = "econml" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/econml-{{ version }}.tar.gz
  sha256: 66542474b2674774cd708b453241495b052307fa162328a5b0c640fd6465bf7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - sphinx <3.2
    - sphinx_rtd_theme
  run:
    - python-graphviz
    - joblib >=0.13.0
    - keras <2.4
    - matplotlib-base
    - numba !=0.42.1
    - numpy
    - pandas <1.1
    - python >=3.6
    - scikit-learn >0.21.0
    - scipy !=1.4.0
    - sparse
    - statsmodels >=0.9
    - tensorflow >1.10,<2.3

test:
  imports:
    - econml
    - econml.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/EconML
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MohammedAjilQC
    - norbertstoopqc
