{% set name = "econml" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/econml-{{ version }}.tar.gz
  sha256: de7a168133d6a92fe967fce79172bdc9c298de9b603afa0fb868dc1797323aff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - dowhy <0.8
    - lightgbm
    - python-graphviz
    - joblib >=0.13.0
    - numba !=0.42.1
    - numpy
    - pandas >1.0
    - python
    - scikit-learn >=1.0,<1.5
    - scipy >1.4.0
    - shap >=0.38.1,<0.44.0
    - sparse
    - statsmodels >=0.10

test:
  imports:
    - econml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/EconML
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
