schema_version: 1

context:
  name: econml
  version: 0.16.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/econml-${{ version }}.tar.gz
  sha256: 4ca862a25e4dd789fd7356adaa04bfed3683056e5d25e90ea75cdab0535d56ff

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scikit-learn >=1.0,<1.7
    - sparse
    - joblib >=0.13.0
    - statsmodels >=0.10
    - pandas >1.0
    - shap >=0.38.1,<0.49.0
    - lightgbm
    - packaging
  run_constrained:
    - dowhy <0.13

tests:
  - python:
      imports:
        - econml
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: MIT AND BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/py-why/EconML

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
    - pavelzw
