schema_version: 1

context:
  name: econml
  version: 0.16.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/econml-${{ version }}.tar.gz
  sha256: 4ca862a25e4dd789fd7356adaa04bfed3683056e5d25e90ea75cdab0535d56ff

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - if: build_platform != target_platform
      then: numpy
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - packaging
    - dowhy <0.8
    - lightgbm
    - python-graphviz
    - joblib >=0.13.0
    - numba !=0.42.1
    - numpy
    - pandas >1.0
    - python
    - scikit-learn >=1.0,<1.7
    - scipy >1.4.0
    - shap >=0.38.1,<0.49.0
    - sparse
    - statsmodels >=0.10

tests:
  - python:
      imports:
        - econml
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/Microsoft/EconML

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
